service: AVA-HIVE-PROD-USERS
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-2
  memorySize: 128
  apiGateway:
    restApiId: wqefm8ssja
    restApiRootResourceId: fp8vr4aezh
functions:
  app:
    handler: src/app.lambdaHandler
    timeout: 30
    events:
      - http:
          path: /users
          method: ANY
          cors: true
      - http:
          path: /users/{proxy+}
          method: ANY
          cors: true
